### ISSUE TITLE
company-edbi is not working.

### ISSUE THREAD

**Issue by stardiviner** [proofit404/company-edbi#1]
After test with `emacs -q`, and load package with `package-initialize`.
Then load `company-mode`, `edbi-minor-mode`, and input text `sele`, then eval elisp `[M-x company-edbi]`. No completing.

**Comment by stardiviner** [comment]
After test, I found auto-complete can work.

**Comment by proofit404** [comment]
In what buffer you type `sele`?

**Comment by stardiviner** [comment]
A file named `test.sql`, major-mode is `sql-mode`.

**Comment by stardiviner** [comment]
Is this company-edbi only works with EDBI opened some database, and only work in EDBI editor buffer?
I thought it can complete common SQL keywords in a normal `sql-mode` buffer.

**Comment by proofit404** [comment]
You understand correctly, this backend works only in edbi query editor buffer.
